### ISSUE TITLE
Bintray "502 Bad Gateway" error

### ISSUE THREAD

**Issue by Quipyowert2** [kwin/cppcheclipse#110] opened 2021-12-11 03:15 UTC
When I try to install cppcheclipse from Eclipse Marketplace, I get the following dialog:
![image](https://user-images.githubusercontent.com/38995150/145661501-b078ae56-83ef-4901-8ac0-fefe0f202dc4.png)

I went to status.bintray.com and it says the bintray service "has now been sunset."

In case it's relevant, my Eclipse version is "Eclipse for C/C++ Developers 2021-12" running on Windows 10. I just installed this version of Eclipse today.

**Comment by kwin** [comment] 2021-12-11 07:23
This is a duplicate of #107.

**Closed** 2021-12-11 07:24 UTC
